name              = input("Nama                  \t: ")
nim               = input("NIM                   \t: ")
parallel_class    = input("Kelas Paralel         \t: ")
birth_place, date = input("Tempat/Tanggal Lahir  \t: ").replace("/", ",", 1).split(",", 1)
address           = input("Alamat                \t: ")
hobby             = input("Hobby                 \t: ")
phone_number      = input("No. HP                \t: ")

print("Nama                 \t:",name)
print("NIM                  \t:",nim)
print("Kelas Paralel        \t:",parallel_class)
print("Tempat/Tanggal Lahir \t:",date,birth_place)
print("Alamat               \t:",address)
print("Hobby                \t:",hobby)
print("No. HP               \t:",phone_number)