print("##############################")
print("#                            #")
print("# Muhammad Adly Noor Habibie #")
print("#       2610817310017        #")
print("#                            #")
print("##############################")